Jb splitfix1
Senzing/g2audit pull request #17
Opened 2021-08-20 04:35 UTC by jbutcher21

This updates corrects the split category when the match could not be found.

2021-08-20 12:30 UTC, antaenc commented on README.md
> +truth set to determine which one is best or to determine the full affect configuration change had against prior run of the same data.  There are many articles that describe this including ...
Shouldn't this be effect not affect

2021-08-20 12:32 UTC, antaenc commented on README.md
> +truth set to determine which one is best or to determine the full affect configuration change had against prior run of the same data.  There are many articles that describe this including ...
Consider either: 

- a configuration change had
- configuration changes had 

"... a prior run..." 

-

2021-08-20 12:33 UTC, antaenc commented on README.md
> +truth set to determine which one is best or to determine the full affect configuration change had against prior run of the same data.  There are many articles that describe this including ...
Dont' use the 3 dots ... like this, use a colon : instead and no space between word and colon

2021-08-20 12:34 UTC, antaenc commented on README.md
> +This project is designed to be used along with ...
Same 3 dots

2021-08-20 12:38 UTC, antaenc commented on README.md
> +                        the ouputfile root name (both a .csv and a .json file
I'd make it clearer this is a dir not a filenmame. 

-o OUTPUTPATH --output_path
                                 the output path (not a filename, both .csv and .json files will be created in this path)

2021-08-20 12:40 UTC, antaenc commented on README.md
> +- python 3.6 or higher
Upper case Python

2021-08-20 12:41 UTC, antaenc commented on README.md
> +10s or 100s of million records, you may need to run this on a computer with enough RAM to load both sets into memory at the same time.*
you will need to

2021-08-20 13:06 UTC, antaenc commented on README.md
> +1. Simply place the the following files in a directory of your choice ...  (Ideally along with G2Snapshot.py and G2Explorer.py)
Simply isn't needed. 3 dots again

2021-08-20 13:07 UTC, antaenc requested changes
Few little clean up items

2021-08-20 17:09 UTC, jbutcher21 commented
Changes made Ant, please review and approve.

2021-08-23 14:26 UTC, antaenc approved these changes

2021-08-23 14:26 UTC, merged